apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: python-api
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/python-api"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
