apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flux-system
  name: python-api-app
  labels:
    app: python-api-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python-api-app
  template:
    metadata:
      labels:
        app: python-api-app
    spec:
      containers:
      - name: python-api-app
        image: ghcr.io/sojay/sample-app:54db676
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: gh-deploy
