apiVersion: v1
kind: Service
metadata:
  name: python-api-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    app: python-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP