apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-docker-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./sample-docker-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
